[2024-12-09T20:24:42.438+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T20:24:42.456+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2024-12-08T00:00:00+00:00 [queued]>
[2024-12-09T20:24:42.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2024-12-08T00:00:00+00:00 [queued]>
[2024-12-09T20:24:42.465+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T20:24:42.477+0000] {taskinstance.py:2889} INFO - Executing <Task(_BranchPythonVirtualenvDecoratedOperator): branching_virtualenv> on 2024-12-08 00:00:00+00:00
[2024-12-09T20:24:42.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_python_operator_decorator', 'branching_virtualenv', 'scheduled__2024-12-08T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator_decorator.py', '--cfg-path', '/tmp/tmp8wxrso8u']
[2024-12-09T20:24:42.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T20:24:42.489+0000] {standard_task_runner.py:105} INFO - Job 256: Subtask branching_virtualenv
[2024-12-09T20:24:42.489+0000] {standard_task_runner.py:72} INFO - Started process 242 to run task
[2024-12-09T20:24:42.539+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_python_operator_decorator.branching_virtualenv scheduled__2024-12-08T00:00:00+00:00 [running]> on host 8553af9ff67b
[2024-12-09T20:24:42.625+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_python_operator_decorator' AIRFLOW_CTX_TASK_ID='branching_virtualenv' AIRFLOW_CTX_EXECUTION_DATE='2024-12-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-08T00:00:00+00:00'
[2024-12-09T20:24:42.628+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T20:24:42.628+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T20:24:42.628+0000] {logging_mixin.py:190} INFO - Current task name:branching_virtualenv state:running start_date:2024-12-09 20:24:42.457280+00:00
[2024-12-09T20:24:42.629+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_python_operator_decorator and current dag run status:running
[2024-12-09T20:24:42.629+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T20:24:42.640+0000] {python.py:809} INFO - Python virtual environment will be cached in /tmp/venv-ebe3c33d
[2024-12-09T20:24:42.645+0000] {python.py:843} WARNING - Found a previous (probably partial installed) virtual environment in /tmp/venv-ebe3c33d, deleting and re-creating.
[2024-12-09T20:24:42.768+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv-ebe3c33d --system-site-packages --python=python
[2024-12-09T20:24:42.770+0000] {process_utils.py:190} INFO - Output:
[2024-12-09T20:24:43.765+0000] {process_utils.py:194} INFO - created virtual environment CPython3.12.7.final.0-64 in 389ms
[2024-12-09T20:24:43.766+0000] {process_utils.py:194} INFO -   creator CPython3Posix(dest=/tmp/venv-ebe3c33d, clear=False, no_vcs_ignore=False, global=True)
[2024-12-09T20:24:43.767+0000] {process_utils.py:194} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-12-09T20:24:43.767+0000] {process_utils.py:194} INFO -     added seed packages: pip==24.3.1
[2024-12-09T20:24:43.768+0000] {process_utils.py:194} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-12-09T20:24:43.793+0000] {process_utils.py:186} INFO - Executing cmd: /tmp/venv-ebe3c33d/bin/pip install -r /tmp/venv-ebe3c33d/requirements.txt
[2024-12-09T20:24:43.794+0000] {process_utils.py:190} INFO - Output:
[2024-12-09T20:24:45.695+0000] {process_utils.py:194} INFO - Collecting numpy~=1.24.4 (from -r /tmp/venv-ebe3c33d/requirements.txt (line 1))
[2024-12-09T20:24:45.698+0000] {process_utils.py:194} INFO -   Using cached numpy-1.24.4.tar.gz (10.9 MB)
[2024-12-09T20:24:46.728+0000] {process_utils.py:194} INFO -   Installing build dependencies: started
[2024-12-09T20:24:50.170+0000] {process_utils.py:194} INFO -   Installing build dependencies: finished with status 'done'
[2024-12-09T20:24:50.171+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: started
[2024-12-09T20:24:50.305+0000] {process_utils.py:194} INFO -   Getting requirements to build wheel: finished with status 'done'
[2024-12-09T20:24:50.535+0000] {process_utils.py:194} INFO - ERROR: Exception:
[2024-12-09T20:24:50.535+0000] {process_utils.py:194} INFO - Traceback (most recent call last):
[2024-12-09T20:24:50.536+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
[2024-12-09T20:24:50.536+0000] {process_utils.py:194} INFO -     status = _inner_run()
[2024-12-09T20:24:50.537+0000] {process_utils.py:194} INFO -              ^^^^^^^^^^^^
[2024-12-09T20:24:50.537+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
[2024-12-09T20:24:50.538+0000] {process_utils.py:194} INFO -     return self.run(options, args)
[2024-12-09T20:24:50.538+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.539+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
[2024-12-09T20:24:50.539+0000] {process_utils.py:194} INFO -     return func(self, options, args)
[2024-12-09T20:24:50.540+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.540+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 379, in run
[2024-12-09T20:24:50.540+0000] {process_utils.py:194} INFO -     requirement_set = resolver.resolve(
[2024-12-09T20:24:50.541+0000] {process_utils.py:194} INFO -                       ^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.541+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
[2024-12-09T20:24:50.542+0000] {process_utils.py:194} INFO -     result = self._result = resolver.resolve(
[2024-12-09T20:24:50.542+0000] {process_utils.py:194} INFO -                             ^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.543+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
[2024-12-09T20:24:50.543+0000] {process_utils.py:194} INFO -     state = resolution.resolve(requirements, max_rounds=max_rounds)
[2024-12-09T20:24:50.543+0000] {process_utils.py:194} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.544+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
[2024-12-09T20:24:50.544+0000] {process_utils.py:194} INFO -     self._add_to_criteria(self.state.criteria, r, parent=None)
[2024-12-09T20:24:50.545+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
[2024-12-09T20:24:50.545+0000] {process_utils.py:194} INFO -     if not criterion.candidates:
[2024-12-09T20:24:50.546+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.546+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
[2024-12-09T20:24:50.547+0000] {process_utils.py:194} INFO -     return bool(self._sequence)
[2024-12-09T20:24:50.547+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.547+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
[2024-12-09T20:24:50.548+0000] {process_utils.py:194} INFO -     return any(self)
[2024-12-09T20:24:50.548+0000] {process_utils.py:194} INFO -            ^^^^^^^^^
[2024-12-09T20:24:50.549+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
[2024-12-09T20:24:50.549+0000] {process_utils.py:194} INFO -     return (c for c in iterator if id(c) not in self._incompatible_ids)
[2024-12-09T20:24:50.549+0000] {process_utils.py:194} INFO -                        ^^^^^^^^
[2024-12-09T20:24:50.550+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
[2024-12-09T20:24:50.550+0000] {process_utils.py:194} INFO -     candidate = func()
[2024-12-09T20:24:50.551+0000] {process_utils.py:194} INFO -                 ^^^^^^
[2024-12-09T20:24:50.551+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 187, in _make_candidate_from_link
[2024-12-09T20:24:50.552+0000] {process_utils.py:194} INFO -     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
[2024-12-09T20:24:50.552+0000] {process_utils.py:194} INFO -                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.553+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 233, in _make_base_candidate_from_link
[2024-12-09T20:24:50.553+0000] {process_utils.py:194} INFO -     self._link_candidate_cache[link] = LinkCandidate(
[2024-12-09T20:24:50.554+0000] {process_utils.py:194} INFO -                                        ^^^^^^^^^^^^^^
[2024-12-09T20:24:50.554+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in __init__
[2024-12-09T20:24:50.555+0000] {process_utils.py:194} INFO -     super().__init__(
[2024-12-09T20:24:50.555+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
[2024-12-09T20:24:50.556+0000] {process_utils.py:194} INFO -     self.dist = self._prepare()
[2024-12-09T20:24:50.556+0000] {process_utils.py:194} INFO -                 ^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.556+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 236, in _prepare
[2024-12-09T20:24:50.557+0000] {process_utils.py:194} INFO -     dist = self._prepare_distribution()
[2024-12-09T20:24:50.557+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.558+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 315, in _prepare_distribution
[2024-12-09T20:24:50.558+0000] {process_utils.py:194} INFO -     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
[2024-12-09T20:24:50.559+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.559+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
[2024-12-09T20:24:50.559+0000] {process_utils.py:194} INFO -     return self._prepare_linked_requirement(req, parallel_builds)
[2024-12-09T20:24:50.560+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.560+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
[2024-12-09T20:24:50.561+0000] {process_utils.py:194} INFO -     dist = _get_prepared_distribution(
[2024-12-09T20:24:50.561+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.561+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
[2024-12-09T20:24:50.562+0000] {process_utils.py:194} INFO -     abstract_dist.prepare_distribution_metadata(
[2024-12-09T20:24:50.562+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
[2024-12-09T20:24:50.563+0000] {process_utils.py:194} INFO -     self._install_build_reqs(finder)
[2024-12-09T20:24:50.564+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
[2024-12-09T20:24:50.564+0000] {process_utils.py:194} INFO -     build_reqs = self._get_build_requires_wheel()
[2024-12-09T20:24:50.565+0000] {process_utils.py:194} INFO -                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.565+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
[2024-12-09T20:24:50.566+0000] {process_utils.py:194} INFO -     return backend.get_requires_for_build_wheel()
[2024-12-09T20:24:50.566+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.567+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 701, in get_requires_for_build_wheel
[2024-12-09T20:24:50.568+0000] {process_utils.py:194} INFO -     return super().get_requires_for_build_wheel(config_settings=cs)
[2024-12-09T20:24:50.569+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.569+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
[2024-12-09T20:24:50.570+0000] {process_utils.py:194} INFO -     return self._call_hook('get_requires_for_build_wheel', {
[2024-12-09T20:24:50.570+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.571+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
[2024-12-09T20:24:50.572+0000] {process_utils.py:194} INFO -     raise BackendUnavailable(data.get('traceback', ''))
[2024-12-09T20:24:50.572+0000] {process_utils.py:194} INFO - pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
[2024-12-09T20:24:50.573+0000] {process_utils.py:194} INFO -   File "/tmp/venv-ebe3c33d/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
[2024-12-09T20:24:50.573+0000] {process_utils.py:194} INFO -     obj = import_module(mod_path)
[2024-12-09T20:24:50.574+0000] {process_utils.py:194} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.574+0000] {process_utils.py:194} INFO -   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
[2024-12-09T20:24:50.575+0000] {process_utils.py:194} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2024-12-09T20:24:50.575+0000] {process_utils.py:194} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-09T20:24:50.576+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[2024-12-09T20:24:50.576+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[2024-12-09T20:24:50.576+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
[2024-12-09T20:24:50.577+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[2024-12-09T20:24:50.577+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[2024-12-09T20:24:50.577+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[2024-12-09T20:24:50.578+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
[2024-12-09T20:24:50.578+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
[2024-12-09T20:24:50.579+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
[2024-12-09T20:24:50.579+0000] {process_utils.py:194} INFO -   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[2024-12-09T20:24:50.579+0000] {process_utils.py:194} INFO -   File "/tmp/pip-build-env-w0yqa1ib/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
[2024-12-09T20:24:50.580+0000] {process_utils.py:194} INFO -     import distutils.core
[2024-12-09T20:24:50.580+0000] {process_utils.py:194} INFO - ModuleNotFoundError: No module named 'distutils'
[2024-12-09T20:24:50.580+0000] {process_utils.py:194} INFO - 
[2024-12-09T20:24:50.730+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 852, in _ensure_venv_cache_exists
    self._prepare_venv(venv_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv-ebe3c33d/bin/pip', 'install', '-r', '/tmp/venv-ebe3c33d/requirements.txt']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 901, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 862, in execute_callable
    venv_path = self._ensure_venv_cache_exists(Path(self.venv_cache_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 856, in _ensure_venv_cache_exists
    raise AirflowException(f"Unable to create new virtual environment in {venv_path}") from e
airflow.exceptions.AirflowException: Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2024-12-09T20:24:50.737+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-09T20:24:50.737+0000] {logging_mixin.py:190} INFO - Task start:2024-12-09 20:24:42.457280+00:00 end:2024-12-09 20:24:50.736593+00:00 duration:8.279313
[2024-12-09T20:24:50.738+0000] {logging_mixin.py:190} INFO - Task:<Task(_BranchPythonVirtualenvDecoratedOperator): branching_virtualenv> dag:<DAG: example_branch_python_operator_decorator> dagrun:<DagRun example_branch_python_operator_decorator @ 2024-12-08 00:00:00+00:00: scheduled__2024-12-08T00:00:00+00:00, state:running, queued_at: 2024-12-09 20:10:07.353973+00:00. externally triggered: False>
[2024-12-09T20:24:50.739+0000] {logging_mixin.py:190} INFO - Failure caused by Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2024-12-09T20:24:50.739+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=example_branch_python_operator_decorator, task_id=branching_virtualenv, run_id=scheduled__2024-12-08T00:00:00+00:00, execution_date=20241208T000000, start_date=20241209T202442, end_date=20241209T202450
[2024-12-09T20:24:50.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T20:24:50.755+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 256 for task branching_virtualenv (Unable to create new virtual environment in /tmp/venv-ebe3c33d; 242)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 852, in _ensure_venv_cache_exists
    self._prepare_venv(venv_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 119, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv-ebe3c33d/bin/pip', 'install', '-r', '/tmp/venv-ebe3c33d/requirements.txt']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 901, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 862, in execute_callable
    venv_path = self._ensure_venv_cache_exists(Path(self.venv_cache_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 856, in _ensure_venv_cache_exists
    raise AirflowException(f"Unable to create new virtual environment in {venv_path}") from e
airflow.exceptions.AirflowException: Unable to create new virtual environment in /tmp/venv-ebe3c33d
[2024-12-09T20:24:50.802+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T20:24:50.835+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T20:24:50.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
